insert into uzytkownik values(1, true, 'asdF123', 'qwer', 'STUDENT',  true);
insert into uzytkownik values(5, true, 'asdF123', 'zxcv', 'STUDENT',  true);
insert into uzytkownik values(2, true, 'asdF123','qwert',  'PRACOWNIK',  true);
insert into uzytkownik values(6, true, 'asdF123','zxcvb',  'PRACOWNIK',  true);
insert into uzytkownik values(3, true, 'asdF123', 'qwerty', 'ADMINISTRATOR', true);
insert into uzytkownik values(4, true, 'asdF123', 'qwera', 'DZIEKAN', true);
insert into uzytkownik values(7, true, 'asdF123', 'zxcva', 'STUDENT',  true);
insert into student values(1, 'ul. Mała 4/14 Kielce','jatyon20@gmail.com', 'Jan', 'Nowak', '23432', '94052234312', 1);
insert into student values(2, 'ul. Sienkiewicza 33/51 Kielce','m.buk@gmail.com', 'Marcin', 'Buk', '25433', '99101363326', 5);
insert into student values(3, 'ul. Sienkiewicza 33/51 Kielce','mateusz.snoch@gmail.com', 'Gawin', 'Norman', '25434', '99101363326', 7);
insert into pracownik_dydaktyczny values(1, 'ul. Ogrodowa 9/45 Kielce', 'jerzy.stonka@gmail.com', 'Jerzy', 'Stonka' ,'79060204628', 2);
insert into pracownik_dydaktyczny values(2, 'ul. Nowa 99/1 Kielce', 'baniah@wp.pl', 'Helena', 'Bania' ,'64110329672', 6);
insert into administrator values(1 , 'ul. Wspólna 37/73 Kielce', 'k.kowal@interia.pl', 'Krzysztof', 'Kowal', '80011165818',3);
insert into dziekan values(1, 'ul. Wesoła 55/34 Kielce', 'f.brzoz@gmail.com', 'Franciszek', 'Brzozowski', '59040812518', 4);
insert into uczelnia values(1, 'Politechnika świętokrzyska', 'aleja Tysiąclecia Państwa Polskiego 7', true);
insert into platnosci values(1, 232, 'NIEZAPLACONE', 'Legitymacja', 1, 1);
insert into platnosci values(2, 532, 'ZAPLACONE','Powtarzanie przedmiotu', 1, 1);
insert into semestr values(1);
insert into semestr values(2);
insert into semestr values(3);
insert into semestr values(4);
insert into semestr values(5);
insert into student_semestr values(1,2);
insert into student_semestr values(2,2);
insert into student_semestr values(3,2);
insert into student_semestr values(4,2);
insert into student_semestr values(5,2);
insert into student_semestr values(1,1);
insert into student_semestr values(2,1);
insert into student_semestr values(3,1);
insert into student_semestr values(4,1);
insert into student_semestr values(5,1);
insert into przedmiot values(1,'Grafika', 1);
insert into przedmiot values(2,'Porgramowanie', 1);
insert into przedmiot values(3,'Bazdy Danych', 2);
insert into przedmiot values(4,'Projektowanie', 2);
insert into przedmiot values(5,'Dobre Wychowanie', 3);
insert into przedmiot values(6,'Muzyka', 3);
insert into przedmiot values(7,'Angielski', 4);
insert into przedmiot values(8,'Projekt Zespolowy', 4);
insert into przedmiot values(9,'Kck', 5);
insert into przedmiot values(10,'WF', 5);
insert into przedmiot_pracownik_dydaktyczny values(1,1);
insert into przedmiot_pracownik_dydaktyczny values(1,2);
insert into przedmiot_pracownik_dydaktyczny values(1,3);
insert into przedmiot_pracownik_dydaktyczny values(1,4);
insert into przedmiot_pracownik_dydaktyczny values(1,5);
insert into przedmiot_pracownik_dydaktyczny values(2,6);
insert into przedmiot_pracownik_dydaktyczny values(2,7);
insert into przedmiot_pracownik_dydaktyczny values(2,8);
insert into przedmiot_pracownik_dydaktyczny values(2,9);
insert into przedmiot_pracownik_dydaktyczny values(2,10);
insert into wnioski values(1, 'ROZPATRZONE','Wniosek nr1.', 'Prosze o stypendium', true, 1, null, 1);
insert into wnioski values(2, 'NIEROZPATRZONE','Wniosek nr2.', 'Prosze o dziekanke', null, 1, null, 1);
insert into wnioski values(3, 'ROZPATRZONE','Wniosek nr1.', 'Prosze o podwyzke', true, 1, 1, null);
insert into wnioski values(4, 'NIEROZPATRZONE','Wniosek nr2.', 'Prosze o wolne', null, 1, 2, null);
insert into wnioski values(5, 'NIEROZPATRZONE','Wniosek nr2.', 'Prosze o wolne', null, 1, 1, null);
insert into wnioski values(6, 'NIEROZPATRZONE','Wniosek nr2.', 'Prosze o wolne', null, 1, 1, null);
insert into przedmiot_student values(1,1);
insert into przedmiot_student values(2,1);
insert into przedmiot_student values(3,1);
insert into przedmiot_student values(4,1);
insert into przedmiot_student values(5,1);
insert into przedmiot_student values(6,1);
insert into przedmiot_student values(7,1);
insert into przedmiot_student values(8,1);
insert into przedmiot_student values(9,1);
insert into przedmiot_student values(10,1);
insert into przedmiot_student values(1,2);
insert into przedmiot_student values(2,2);
insert into przedmiot_student values(3,2);
insert into przedmiot_student values(4,2);
insert into przedmiot_student values(5,2);
insert into przedmiot_student values(6,2);
insert into przedmiot_student values(7,2);
insert into przedmiot_student values(8,2);
insert into przedmiot_student values(9,2);
insert into przedmiot_student values(10,2);
insert into ocena values(1,3,1,1);
insert into ocena values(2,4,2,1);
insert into ocena values(3,5,3,1);
insert into ocena values(4,3,4,1);
insert into ocena values(5,5,5,1);
insert into ocena values(6,3,6,1);
insert into ocena values(7,3,1,2);
insert into ocena values(8,4,2,2);
insert into ocena values(9,5,3,2);
